<?php
/**
 * @file
 * Code for the pokedex_v2 feature.
 */

include_once 'pokedex_v2.features.inc';

/**
 * Implements hook_ds_fields_info().
 */
function pokedex_v2_ds_fields_info($entity_type) {
  $fields = array();
  $fields['next_pokemon'] = array(
      'title' => t('Next Pokemon'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => 'pokedex_v2_ds_field_next_pokemon',
    );
  $fields['prev_pokemon'] = array(
      'title' => t('Previous Pokemon'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => 'pokedex_v2_ds_field_prev_pokemon',
    );
  $fields['stats_as_bars'] = array(
    'title' => t('Stats Percentage Bars'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'function' => 'pokedex_v2_ds_field_stats_as_bars',
    'properties' => array(
      'formatters' => array(
        'stats_as_bars' => 'Percentage Bars',
      ),
    ),
  );

  return array('node' => $fields,);
}


/*
 * Store next pokemon by number.
 */
function pokedex_v2_ds_field_next_pokemon($field){
  //entity we are working with (pokemon)
  $entity = $field['entity'];
  $number = $entity->field_number['und'][0]['value'];
  //numbers are stored as 3 digit strings: "005"
  $next = sprintf("%03d", $number+1);
  //db query to get next pokemon nid
  $query = db_select( 'field_data_field_number', 'n');
  $query
    ->condition('field_number_value', $next, '=')
    ->fields('n', array('entity_id'));
  $result = $query->execute();
  //get node from nid
  foreach( $result as $record){
    $pokemon_id = $record->entity_id;
  }
  //load for access to fields
  $pokemon = node_load($pokemon_id);
  //create output
  $output = '';
  $output .= '<i class="fa fa-angle-double-right" aria-hidden="true"></i>';
  $output .= '<p>' . $pokemon->title . '</p>';
  $output .= '<p>' . $pokemon->field_number['und'][0]['value'] . '</p>';
  //wrap in link
  $output = l($output, 'node/'. $pokemon->nid, array('html' => TRUE));
  return $output;
}

function pokedex_v2_ds_field_prev_pokemon($field){
  //entity we are working with (pokemon)
  $entity = $field['entity'];
  $number = $entity->field_number['und'][0]['value'];
  //numbers are stored as 3 digit strings: "005"
  $prev = sprintf("%03d", $number-1);
  //db query to get next pokemon nid
  $query = db_select( 'field_data_field_number', 'n');
  $query
    ->condition('field_number_value', $prev, '=')
    ->fields('n', array('entity_id'));
  $result = $query->execute();
  //get node from nid
  foreach( $result as $record)
  $pokemon_id = $record->entity_id;
  //load for access to fields
  $pokemon = node_load($pokemon_id);
  //create output
  $output = '';
  $output .= '<i class="fa fa-angle-double-left" aria-hidden="true"></i>';
  $output .= '<p>' . $pokemon->title . '</p>';
  $output .= '<p>' . $pokemon->field_number['und'][0]['value'] . '</p>';
  //wrap in link
  $output = l($output, 'node/'. $pokemon->nid, array('html' => TRUE));
  return $output;
}

/*
 * Displays the 3 stats of a pokemon as Bars
 */
function pokedex_v2_ds_field_stats_as_bars($field){
  // Get information about the entity being rated and the formatter we're using.
  $entity = $field['entity'];
  $formatter = $field['formatter'];
  //maxes
  $max_stam = 510;
  $max_atk = 330;
  $max_def = 396;
  //percents
  $perc_stam = $entity->field_stamina['und'][0]['value']/$max_stam*100;
  $perc_stam = sprintf("%02.0f", $perc_stam);
  $perc_atk = $entity->field_attack['und'][0]['value']/$max_atk*100;
  $perc_atk = sprintf("%02.0f", $perc_atk);
  $perc_def = $entity->field_defense['und'][0]['value']/$max_def*100;
  $perc_def = sprintf("%02.0f", $perc_def);
  $percentages = array(
    $entity->field_stamina['und'][0]['value'] => $perc_stam,
    $entity->field_attack['und'][0]['value'] => $perc_atk,
    $entity->field_defense['und'][0]['value'] => $perc_def,
  );
  //get color of first type of the pokemon
  $color = $entity->field_type['und'][0]['taxonomy_term']->field_type_color;

 if ($formatter == 'stats_as_bars'){
   //for all three stats
   foreach($percentages as $stat => $percent){
     //inner bar has % width
     $output = '<div class="inner-percentage-bar" style="';
     $output .= 'width:'. $percent . '%;';
     //background color matches type
     $output .= 'background-color: '. $color . ';">';
     //and has the stat inside
     $output .= $stat. '</div>';
     //wrap a div around it with grey background
     $output = '<div class="outer-percentage-bar" style="background: #676767;">'. $output .'</div>';
   }
 }

 return $output;
}
